---
- hosts: pi
  become: yes
  vars:
    project_base_path: /opt/py-agent/
  tasks:
  - name: create base path
    file:
      path: "{{ project_base_path }}"
      state: directory
  - name: create base data path
    file:
      path: "{{ project_base_path }}/data/"
      state: directory
  - name: copy src to host
    copy:
      src: src/
      dest: "{{ project_base_path }}"
  - name: build images
    docker_image:
      build:
        path: "{{ project_base_path }}"
      name: py_agent
      source: build
      force_source: yes
    register: out
    
  - debug: var=out

  - name: start service
    docker_container:
      name: py_agent
      image: py_agent
      state: started
      restart: yes
      restart_policy: always
      volumes:
        - "{{ project_base_path }}/data:/opt/data/"
      env:
        PY_AGENT_DB_PATH: /opt/data/db.sqlite
